### ISSUE TITLE
Is there a way to use private key and certificate that is stored in HSM to be used for client authentication in TLS handshake?

### ISSUE THREAD

**Issue by batuhanceylan** [danni/python-pkcs11#67]
Is there a way to use private key and certificate that is stored in HSM to be used for client authentication in TLS handshake?

Hi,

I'm trying to establish TLS channel between two devices where private key and certificate are stored in HSM. Is there a way for a TLS client trying to authenticate itself to TLS server via TLS mutual authentication, where both the private key and corresponding certificate are stored in HSM?

I have tried several other libraries (pyopenssl, pycurl, requests, etc.) with no luck. Nothing related to TLS + PKCS11 has mentioned in docs including pycurl. There's a possibility I'm missing something obvious as it's hard to believe that none of these libraries have PKCS11 support. I welcome any library or workaround recommendation.

**Comment by inorton** [comment]
PKCS11 provides all the Cryptography functions used to implement TLS.

There are other projects like "libp11" that allow openssl to use pkcs11 drivers

**Comment by danni** [comment]
We've not implemented any of this because there are canonical implementations available, e.g. using your HSM via the PKCS#11 OpenSSL engine. Check the OpenSSL docs for how to do this, and then use OpenSSL with `requests` (etc.)

Even things X.509 like certificate creation and validation are often better via OpenSSL + the engine. You're less likely to make a mistake if you avoid reinventing the wheel altogether. Unfortunately it's hard to use an engine via PyOpenSSL so the original motivation for this package was only to provide streaming cryptographic primitives using key and certificate material produced elsewhere.

**Comment by batuhanceylan** [comment]
> There are other projects like "libp11" that allow openssl to use pkcs11 drivers

@inorton I was looking for python way of dealing with TLS and PKCS#11

> We've not implemented any of this because there are canonical implementations available, e.g. using your HSM via the PKCS#11 OpenSSL engine. Check the OpenSSL docs for how to do this, and then use OpenSSL with `requests` (etc.)

@danni do you know of any examples I can follow?

**Comment by danni** [comment]
See https://github.com/OpenSC/libp11#openssl-engines

**Comment by batuhanceylan** [comment]
@danni I have already managed to use libp11 engine to do tls mutual authentication using openssl's s_server and s_client. However, I couldn't find any resource to enable engine functionality in python. How come you achieved that? Did you compile openssl/libp11 in a certain way to always use a specific engine when, let's say, requests library is used?

**Comment by hablutzel1** [comment]
You can do it quite simply using M2Crypto as described in https://stackoverflow.com/a/78619062/320594
